### ISSUE TITLE
Check for errors in response from rorocloud in _request method.

### ISSUE THREAD

**Issue by sohail535** [rorodata/rorocloud#3]
```
$ rorocloud run echo hello
Traceback (most recent call last):
  File "/home/sohail/rorodata/rorocloud/venv/bin/rorocloud", line 11, in <module>
    load_entry_point('rorocloud', 'console_scripts', 'rorocloud')()
  File "/home/sohail/rorodata/rorocloud/rorocloud/cli.py", line 187, in main
    cli()
  File "/home/sohail/rorodata/rorocloud/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sohail/rorodata/rorocloud/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sohail/rorodata/rorocloud/venv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sohail/rorodata/rorocloud/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sohail/rorodata/rorocloud/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sohail/rorodata/rorocloud/rorocloud/cli.py", line 70, in run
    _run(command, shell=shell, workdir=workdir, foreground=foreground)
  File "/home/sohail/rorodata/rorocloud/rorocloud/cli.py", line 73, in _run
    job = client.run(command, shell=shell, workdir=workdir)
  File "/home/sohail/rorodata/rorocloud/rorocloud/client.py", line 88, in run
    return Job(data)
  File "/home/sohail/rorodata/rorocloud/rorocloud/client.py", line 109, in __init__
    self.id = data['jobid']
KeyError: 'jobid'
```

Any command that is run in rorocloud is not checking for an error response from rorocloud.
I ran the above command after removing ~/.rorocloudrc

**Comment by anandology** [comment]
I think the _request method should return the response object and each
method calling it should check the status code and raise appropriate error
message.
